---
- name: ensure Prometheus exporters directory exist
  file:
    path: "{{ redis_exporter_install_dir }}"
    state: directory

- name: create redis-exporter folder
  file:
    path: "{{ redis_exporter_install_dir }}/{{ redis_exporter_name }}"
    state: directory

- name: unarchive Redis Exporter
  unarchive:
    remote_src: yes
    dest: "{{ redis_exporter_install_dir }}/{{ redis_exporter_name }}"
    src: "{{ redis_exporter_url }}"

- name: create symlink to the current release
  file:
    src: "{{ redis_exporter_binary }}"
    path: "{{ redis_exporter_symlink }}"
    state: link
  notify: restart redis exporter

- name: create systemd script
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis-exporter.service
  notify: restart redis exporter

- meta: flush_handlers

- name: make sure Redis Exporter is started
  service:
    name: redis-exporter
    state: started
    enabled: yes